[package]
name = "poe_query"
version = "0.1.0"
authors = ["Daniel Dimovski <daniel.k.dimovski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poe_bundle_reader = { git = "https://github.com/daniel-dimovski/poe-bundle-reader" }
pest = "2.1.3"
pest_derive = "2.1.0"

memmap = "0.7.0"
byteorder = "1.3.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0.59"
clap = "2.33.3"
