[package]
name = "poe_query"
version = "0.1.18"
authors = ["Daniel <daniel@timeloop.se>"]
edition = "2021"

[[bin]]
name = "poe_query"
path = "src/main.rs"

[lib]
name = "poe_query_lib"
path = "src/lib.rs"

[dependencies]
poe_bundle = "0.2.0"
log = "0.4.11"
simplelog = "0.12.0"
clap = { version = "4.5", features = ["derive"] }

pest = "2.4"
pest_derive = "2.1.0"
apollo-parser = "0.3.1"

thiserror = "1.0"
strsim = "0.11"
byteorder = "1.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
